name: Validate workflows

on:
  pull_request:
    paths: [.github/actions/**, .github/workflows/**]
  push:
    branches: [main]
    paths: [.github/actions/**, .github/workflows/**]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.7
      - run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: actionlint -ignore 'SC(2016|2035|2129)'
